module.exports = {
	lastModified: -1,
	description: 'Representation of the data subject',
	attributes: [{
		dataType: 'Text',
		sensitive: false,
		personal: false,
		sealed: false,
		keyUnique: false,
		indexed: false,
		generated: false,
		description: '',
		defaultValue: '',
		validation: [Object],
		pseudoFn: 'return document[attributeName]',
		access: [Object],
		uid: '',
		sid: '',
		timestamp: [Object],
		name: [Object],
		fixed: false,
		active: true
	},
	{
		name: 'uid',
		description: '',
		type: 'Text',
		sensitive: true,
		personal: true,
		sealed: true,
		unique: true,
		indexed: false,
		generated: true,
		fixed: true,
		defaultValue: '',
		pseudoFn: 'return clerobee.generate(8)',
		uid: '',
		timestamp: -1,
		active: true,
		validation: [Object],
		access: [Object]
	},
	{
		name: 'sid',
		description: '',
		type: 'Text',
		sensitive: true,
		personal: true,
		sealed: true,
		unique: false,
		indexed: false,
		generated: false,
		fixed: true,
		defaultValue: '',
		pseudoFn: 'return clerobee.generate(8)',
		uid: '',
		timestamp: -1,
		active: true,
		validation: [Object],
		access: [Object]
	},
	{
		name: 'exp_uid',
		description: '',
		type: 'Text',
		sensitive: false,
		personal: true,
		sealed: false,
		unique: true,
		indexed: false,
		generated: true,
		fixed: true,
		defaultValue: '',
		pseudoFn: 'return clerobee.generate(8)',
		uid: '',
		timestamp: -1,
		active: true,
		validation: [Object],
		access: [Object]
	},
	{
		name: 'timestamp',
		description: '',
		type: 'Timestamp',
		sensitive: false,
		personal: false,
		sealed: false,
		unique: false,
		indexed: false,
		generated: true,
		fixed: true,
		defaultValue: '-1',
		pseudoFn: 'return -1',
		uid: '',
		timestamp: -1,
		active: true,
		validation: [Object],
		access: [Object]
	},
	{
		name: 'consent',
		description: '',
		type: 'Object',
		sensitive: true,
		personal: true,
		sealed: false,
		unique: false,
		indexed: false,
		generated: false,
		fixed: true,
		defaultValue: [Object],
		uid: '',
		timestamp: -1,
		active: true,
		validation: [Object],
		access: [Object]
	},
	{
		name: 'active',
		description: '',
		type: 'Boolean',
		sensitive: false,
		personal: false,
		sealed: false,
		unique: false,
		indexed: false,
		generated: false,
		fixed: true,
		defaultValue: 'true',
		uid: '',
		timestamp: -1,
		active: true,
		validation: [Object],
		access: [Object]
	},
	{
		name: 'authID',
		description: '',
		type: 'Text',
		sensitive: false,
		personal: false,
		sealed: false,
		unique: true,
		indexed: false,
		generated: true,
		fixed: true,
		defaultValue: '',
		pseudoFn: 'return clerobee.generate(8)',
		uid: '',
		timestamp: -1,
		active: true,
		validation: [Object],
		access: [Object]
	},
	{
		name: 'authKey',
		description: '',
		type: 'Text',
		sensitive: false,
		personal: false,
		sealed: false,
		unique: true,
		indexed: false,
		generated: true,
		fixed: true,
		defaultValue: '',
		pseudoFn: 'return clerobee.generate(8)',
		uid: '',
		timestamp: -1,
		active: true,
		validation: [Object],
		access: [Object]
	},
	{
		name: 'email',
		description: '',
		type: 'Text',
		sensitive: false,
		personal: false,
		sealed: false,
		unique: false,
		indexed: false,
		generated: false,
		fixed: true,
		defaultValue: '',
		uid: '',
		timestamp: -1,
		active: true,
		validation: [Object],
		access: [Object]
	},
	{
		name: 'phone',
		description: '',
		type: 'Text',
		sensitive: false,
		personal: false,
		sealed: false,
		unique: false,
		indexed: false,
		generated: false,
		fixed: true,
		defaultValue: '',
		uid: '',
		timestamp: -1,
		active: true,
		validation: [Object],
		access: [Object]
	} ],
	access: {
		confidant: {
			pseudo: false,
			minimised: false,
			write: true
		},
		dpo: {
			pseudo: false,
			minimised: false,
			write: true
		},
		controller: {
			pseudo: false,
			minimised: false,
			write: true
		},
		processor: {
			pseudo: false,
			minimised: false,
			write: true
		},
		thirdparty: {
			pseudo: false,
			minimised: false,
			write: false
		},
		recipient: {
			pseudo: false,
			minimised: false,
			write: false
		},
		manager: {
			pseudo: false,
			minimised: false,
			write: false
		},
		developer: {
			pseudo: false,
			minimised: false,
			write: true
		},
		deployer: {
			pseudo: false,
			minimised: false,
			write: false
		},
		tester: {
			pseudo: false,
			minimised: false,
			write: true
		},
		analyser: {
			pseudo: false,
			minimised: false,
			write: false
		},
		marketer: {
			pseudo: false,
			minimised: false,
			write: false
		}
	},
	uid: '',
	sid: '',
	timestamp: -1,
	name: 'Subject',
	fixed: false,
	active: true
}
